# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claws < Formula
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clawscli/claws/releases/download/v0.1.2/claws-darwin-amd64.tar.gz"
      sha256 "49f20904b5b4fc631cb9e49e46b7280a0f0cc1039ae9b41cb48119b1fd815a4e"

      def install
        bin.install "claws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clawscli/claws/releases/download/v0.1.2/claws-darwin-arm64.tar.gz"
      sha256 "307692758656e8b64990c7ad71fc37f9abb1c0f0dd05d5ad19ad7e47ef292237"

      def install
        bin.install "claws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawscli/claws/releases/download/v0.1.2/claws-linux-amd64.tar.gz"
      sha256 "28ee6d86c7ce2d22d0c80a80a40961864133133526163a6d16188c3d9ae47b5e"
      def install
        bin.install "claws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawscli/claws/releases/download/v0.1.2/claws-linux-arm64.tar.gz"
      sha256 "7726a2988827a0207e4a8c04bc196e850644589bd809f08fd5d66bf8426923ea"
      def install
        bin.install "claws"
      end
    end
  end

  test do
    system "#{bin}/claws", "--help"
  end
end
