# This file was generated by GoReleaser. DO NOT EDIT.
cask "claws" do
  name "claws"
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claws"

  on_macos do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-amd64.tar.gz"
      sha256 "bd2df8cc91867fe7c8aae20ad86d79b8a6ee9e3a054532b4738f7d5c9e8679fe"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-arm64.tar.gz"
      sha256 "2d3408bf67606e32073dc287b11c0751e1833a01b084e6d6e389c9af108254ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-amd64.tar.gz"
      sha256 "9a76628e207d65e6f9aab740f1a73aa3ed839016411c743e5e4e3570f015fae3"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-arm64.tar.gz"
      sha256 "84cf6fcef1131735a88c75d6367967108bc018a39db133fbcc19f3fead128f83"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
    end
  end

  # No zap stanza required
end
