# This file was generated by GoReleaser. DO NOT EDIT.
cask "claws" do
  name "claws"
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"
  version "0.12.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claws"

  on_macos do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-amd64.tar.gz"
      sha256 "f78d8da7e1ea7933d35ec6e953008476072a0978b504cb68ab5dd60794420964"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-arm64.tar.gz"
      sha256 "181f62fc3277929a312633470d294698184b6068964fcb96e40d315525eb757d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-amd64.tar.gz"
      sha256 "3c276d773dc4b7b3ea1456e9b98318159f3a881930c64b7c484e902080831210"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-arm64.tar.gz"
      sha256 "b849a691abd01f09277d8657e57f27ddc73e81dea97d232d3d4032c3d606dce6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
    end
  end

  # No zap stanza required
end
