# This file was generated by GoReleaser. DO NOT EDIT.
cask "claws" do
  name "claws"
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claws"

  on_macos do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-amd64.tar.gz"
      sha256 "0d8113568095d4f2df97af1902cb428dc6c4c3b4237cfbdb7faa44023ca91f69"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-arm64.tar.gz"
      sha256 "d393b3263f4b2945a06b0b747a2d07771d9c4edce169fc3e30f2004da738cfc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-amd64.tar.gz"
      sha256 "4297e06d24206f638a991412940be48709ea7df0dfc0546c5510676a4f7d0e4f"
    end
    on_arm do
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-arm64.tar.gz"
      sha256 "1f41ef7ec614d2c42f78f65e63eb500fa5ea1b029ccd51a870c299ef296bfb1c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
    end
  end

  # No zap stanza required
end
